### ISSUE TITLE
Add support for private images

### ISSUE THREAD

**Issue by GalacticLion7** [digitalocean/marketplace-partners#105]

**Comment by jgannondo** [comment]
Hi @GalacticLion7 - thanks for filing this. Can you share some more details on what you're looking for?

**Comment by GalacticLion7** [comment]
> Hi @GalacticLion7 - thanks for filing this. Can you share some more details on what you're looking for?

Like a “private Marketplace” that has images that only you or your team can access.

**Comment by jgannondo** [comment]
@GalacticLion7 mind emailing me on jgannon@do.co ? I'd love to learn more about what you are trying to do.

**Comment by jgannondo** [comment]
Hey there @GalacticLion7 -- I'm going to close this out, but feel free to email me directly to discuss. Or re-open this issue if it is still relevant. Thanks!

**Comment by blackrangersoftware** [comment]
@GalacticLion7 That functionality exists already, in that you can import a custom image, and when you do they are only available to you and your users.
 
https://docs.digitalocean.com/products/images/custom-images/
 https://docs.digitalocean.com/products/images/custom-images/how-to/upload/
