### ISSUE TITLE
Issue a FAIL if a Snapshot has the do-agent enabled, and provide instructions in the output for how to remove it

### ISSUE THREAD

**Issue by jgannondo** [digitalocean/marketplace-partners#11]
Insights Agent reports back to the data collection service by default. If a snapshot is converted to a Marketplace image, we should ensure that insights is removed as the customer wouldn't be explicitly desiring to use it.

**Comment by ryanpq** [comment]
Fixed in PR https://github.com/digitalocean/marketplace-partners/pull/13
