### ISSUE TITLE
Add examples of how to use DigitalOcean Droplet Metadata service to configure initial passwords for webapps

### ISSUE THREAD

**Issue by jgannondo** [digitalocean/marketplace-partners#114]
We have a Vendor that uses Droplet Metadata to generate a unique password for the webapp in their 1-Click, using a call like this:

`curl http://169.254.169.254/metadata/v1/id -w "\n"`

Could we create an example for some common frameworks so that Vendors can more easily take the same approach?

This method for password generation within a webapp would be more secure than defaults like admin/admin.

**Comment by arosales** [comment]
I like the idea of user Droplet Metadata. Could you help me understand how we use this to set passwords for users? Specifically, what is the UX at deploy and/or post deploy time. How is the password set, kept safe, and then read by the user?

**Comment by arosales** [comment]
My concern with this curl is it is non-authenticated. I am guessing it relies on firewall rules to protect the data, but given its not authenticated we should think through this being the recommended approach.

Could we just do random password generation on the droplet itself? 
https://help.ubuntu.com/community/StrongPasswords
https://www.howtogeek.com/howto/30184/10-ways-to-generate-a-random-password-from-the-command-line/

We would need to think though how to store and have the user read them securely as well.

**Comment by arosales** [comment]
On further research to better understand DO's metadata service I know understand querying the Droplet's `id` can only be done from the Droplet. That makes more sense in this context. Thanks for the clarification @jgannondo

**Comment by arosales** [comment]
To close on this thread I chatted with the security team and they had some concerns with the meata-data approach, and ultimately suggested to do something like:

`gpg --gen-random --armor 2 12 > /root/.secrets.txt `

Then have the user read out /root/.secrets.txt
