### ISSUE TITLE
MOTD not displaying by default (ubuntu 20.04)

### ISSUE THREAD

**Issue by SelfhostedPro** [digitalocean/marketplace-partners#116]
It looks like `PrintMotd no` is the default on the ubuntu 20.04 images so my motd isn't displaying. Is there another way to display helpful information to users on first login or should I just include the correct sshd_config in my packer build?

**Comment by pachamaltese** [comment]
Hi @SelfhostedPro 
Last week I had a few problems with these new Ubuntu settings. I'd recommend using Ubuntu 18.04 LTS for now. You can always change `sshd_config` and add your own messages before submitting the image.
