### ISSUE TITLE
Add support for suppressing warnings on img_check.sh

### ISSUE THREAD

**Issue by caquillo07** [digitalocean/marketplace-partners#119]
Currently the img_check.sh prints out all success, warnings and errors that it found on a given image. 

We should add an optional flag to suppress warnings from the output in order to reduce noise, and not providing this flag defaults to the current behavior.

**Comment by jgannondo** [comment]
I'm going to close this one @caquillo07 as I don't think it's been a blocker to the recent improvements or planned improvements to img_check. Feel free to re-open if I've missed the 🚢  on this one :)
