### ISSUE TITLE
Cleanup.sh does not remove the root password

### ISSUE THREAD

**Issue by william-stearns** [digitalocean/marketplace-partners#134]
cleanup.sh does not currently remove or offer to remove root's password.  I do realize this is somewhat of a final step, but note that once cleanup is run it's no longer possible to log in over ssh anyways as the ssh keys are gone.

At the end of this message is a sample script for removing root's password.  You're welcome to merge into cleanup.sh, leave as a separate script, or ignore entirely.

(Brought up here for discussion; if you like the idea I'm happy to submit a pull request.)

erase_root_password.sh

#!/bin/bash

if [ "$EUID" -ne 0 ]
        then echo "[Error] - This script must be run with sudo or as the root user."
        exit 1
fi

echo "Would you like to erase the root password?  If you answer   YES   you will no longer be able to log in as root."
read answer
if [ "$answer" = "YES" ]; then
        echo "Erasing root password"
        sed -i'' 's/^\(root:\)[^:]*\(:.*\)$/\1\*\2/' /etc/shadow
        if grep -q '^root:\*:' /etc/shadow
                echo "It appears root's password has been disabled successfully."
        else
                echo "Warning: it appears root's password has NOT been disabled."
        fi
else
        echo "NOT erasing root password."
fi

**Comment by pachamaltese** [comment]
fixed in https://github.com/digitalocean/marketplace-partners/pull/132
