### ISSUE TITLE
`img_check.sh` failed on Droplet because of droplet-agent

### ISSUE THREAD

**Issue by alallema** [digitalocean/marketplace-partners#164]
**Issue**
Since this PR #156 all the directory `/opt/digitalocean` is checked out, but by default, a droplet agent is installed there.
So the script `img_check.sh` script automatically fails when I test it on Droplet.

**Screenshot**
<img width="930" alt="Screenshot 2022-09-29 at 14 54 52" src="https://user-images.githubusercontent.com/16155041/193036842-3372b38a-f09e-4451-ade1-fb5554e99982.png">

My question is this the expected behavior? Did I have to use [this](https://docs.digitalocean.com/products/droplets/how-to/manage-agent/#uninstalling-the-droplet-agent) before passing my script? I also had a `/opt/digitalocean/bin`.

**Comment by alallema** [comment]
I finally run this command and it's working well:
```
apt-get purge droplet-agent* -y
```

**Comment by actorTian** [comment]
didn't work
