### ISSUE TITLE
Debian 12 support

### ISSUE THREAD

**Issue by wolfsoft** [digitalocean/marketplace-partners#178]
I think that stable Debian 12 (bookworm) is already supported by DO. Could you please add the
```
elif [[ "$OS" =~ Debian.* ]]; then
    ost=1
    case "$VER" in
        9)
            osv=1
            ;;
        10)
            osv=1
            ;;
        11)
            osv=1
            ;;
```
```
        12)
            osv=1
            ;;
```
into the 99-img-check.sh file?

**Comment by keladhruv** [comment]
Thanks for creating the issue, [Relevant PR](https://github.com/digitalocean/marketplace-partners/pull/179).
