### ISSUE TITLE
Add Terraform sample code for automated droplet creation for marketplace

### ISSUE THREAD

**Issue by ryan-blunden** [digitalocean/marketplace-partners#27]
Would love to see an example using Terraform to create the image.

**Comment by gunnaraasen** [comment]
[Packer](https://www.packer.io/docs/builders/digitalocean.html) should also be looked at, especially since there's already a DO builder.

**Comment by scott** [comment]
I have been playing with packer but have not succeeded yet.  Would love to see a working example.

**Comment by andrewsomething** [comment]
Packer is a great tool for this sort of use case. I threw together what is pretty much a straight port of the example using Fabric in this repo.

Check it out here: https://github.com/andrewsomething/digitalocean-marketplace-packer

One thing to note is that the image validation script there has been copied here from this repo. This is its canonical source. So if you use the Packer example, make sure you are using the latest version of that script from this repository.

**Comment by pyToshka** [comment]
@ryan-blunden Terraform this is tool for deployment new infrastructure, not for building images.
Terraform couldn't create your own image by default

**Comment by jgannondo** [comment]
Since this issue was opened, we added some automation for Packer based builds: https://github.com/digitalocean/marketplace-partners/tree/master/packer

// @gunnaraasen
