### ISSUE TITLE
centos 7 /etc/shadow user password check

### ISSUE THREAD

**Issue by centminmod** [digitalocean/marketplace-partners#33]
On centos 7.6 64bit for img_check.sh check for users with passwords set at /etc/shadow both nginx and memcached user for my Centmin Mod LEMP stack installs is marked as a FAILED check but I have not set any passwords on those ?

```
egrep 'root|nginx|memcached|mysql' /etc/shadow
root:*:16176:0:99999:7:::
nginx:!!:17961:0:99999:7:::
mysql:!!:17961::::::
memcached:!!:17961:0:99999:7:::
```

```
Checking all user-created accounts...

Checking user: nginx...
[FAIL] User nginx has a password set on their account.
[ OK ] User nginx does not have an .ssh directory

Checking user: memcached...
[FAIL] User memcached has a password set on their account.
[ OK ] User memcached does not have a directory in /home


Checking the root account...
[PASS] User root has no password set.
[ OK ] User root has no SSH keys present
[PASS] root's Bash History appears to have been cleared
[PASS] DigitalOcean Monitoring agent was not found
```

`bash -x img_check.sh` output excerpts

```
+ for usr in '$SHADOW'
+ IFS=:
+ read -r -a u
+ [[ nginx == \n\g\i\n\x ]]
+ [[ !! == \! ]]
+ [[ !! == \* ]]
+ echo -en '\e[41m[FAIL]\e[0m User nginx has a password set on their account.\n'
[FAIL] User nginx has a password set on their account.
+ (( FAIL++ ))
+ STATUS=2
```

```
+ for usr in '$SHADOW'
+ IFS=:
+ read -r -a u
+ [[ memcached == \m\e\m\c\a\c\h\e\d ]]
+ [[ !! == \! ]]
+ [[ !! == \* ]]
+ echo -en '\e[41m[FAIL]\e[0m User memcached has a password set on their account.\n'
[FAIL] User memcached has a password set on their account.
+ (( FAIL++ ))
+ STATUS=2
```

seems img_check.sh is looking for `!` while centos 7 for user accounts which are locked without password set show up as `!!` instead https://unix.stackexchange.com/a/252019/26581

> Both "!" and "!!" being present in the password field mean an account is locked.
> As it can be read in the following document, "!!" in an account entry in shadow means the account of an user has been created, but not yet given a password. Until being given an initial password by a sysadmin, it is locked by default.

> This maybe true on Red Hat systems, but not necessarily elsewhere - on Ubuntu or Arch Linux, a newly-created account with no password still has only !, not !!

so you may need a separate check for redhat/centos for no password set = `!!` while ubuntu and non-redhat/centos for no password set = `!` ?

or just change line 

from

```
if [[ ${u[1]} == "!" ]] || [[ ${u[1]} == "*" ]]; then
```

to

```
if [[ ${u[1]} == "!" ]] || [[ ${u[1]} == "!!" ]] || [[ ${u[1]} == "*" ]]; then
```

then img_check.sh run would end up as

```
Checking all user-created accounts...

Checking user: nginx...
[PASS] User nginx has no password set.
[ OK ] User nginx does not have an .ssh directory

Checking user: memcached...
[PASS] User memcached has no password set.
[ OK ] User memcached does not have a directory in /home


Checking the root account...
[PASS] User root has no password set.
[ OK ] User root has no SSH keys present
[PASS] root's Bash History appears to have been cleared
[PASS] DigitalOcean Monitoring agent was not found
```

**Comment by qrkourier** [comment]
When the expected `!` value is used for the password field [1] CentOS treats the password as expired and prompts for a reset but always fails. The result is the same whether UsePam is yes or no in sshd_config. With `!!` effectively prevents login with a password which is desired for launching droplets with an SSH pubkey, but upon login the user is still prompted to change their password and re-login. That new password will still be used for `sudo`, depending on the custom image configuration, but not for SSH login which is perfectly fine. I second the motion to change the img_chk script to expect `!!`.

**Comment by qrkourier** [comment]
Correction to the above: when password value is `!!` I can not log in despite having a pubkey authorization with sshd_config set to
```
UsePAM yes # required for CentOS
PasswordAuthentication no
PubkeyAuthentication yes
```
```
WARNING: Your password has expired.
You must change your password now and login again!
Changing password for user qrkourier.
Changing password for qrkourier.
(current) UNIX password:
passwd: Authentication token manipulation error
```
and the ssh journal says
```
Mar 15 21:27:28 droplet1 passwd: pam_unix(passwd:chauthtok): authentication failure; logname=qrkourier uid=1000 euid=0 tty=pts/2 ruser= rhost=  user=qrkourier
```

**Comment by qrkourier** [comment]
The only solution I see at the moment is leaving the intended priviledged user's password empty in the sealed OS image and requiring an SSH pubkey for login in sshd_config.

**Comment by qrkourier** [comment]
The problem was that password reset was being forced with `chage --lastday 0 $USERNAME` in the script that seals the image prior to shutdown. This caused login to fail despite PasswordAuthentication=no and PubkeyAuthentication=yes because a password reset is required to login. Now, without the `chage` command, and with a password value in /etc/shadow of `!!` the image is secure and login works.
