### ISSUE TITLE
first boot /opt/vendorname/script.sh interactive works on droplet rebuilds ?

### ISSUE THREAD

**Issue by centminmod** [digitalocean/marketplace-partners#36]
In instructions at https://github.com/digitalocean/marketplace-partners/blob/master/marketplace_docs/build-an-image.md#running-commands-or-interactive-scripts-on-first-login it says to setup /opt/vendorname/script.sh for interactive first login setups and that on creating a new droplet with the snapshot image, it will trigger the script. However, is the same true for when you rebuild a droplet with the same snapshot image ? I setup my snapshot image built with packer.io with CentOS 7 with the following at `/opt/centminmod`

```
ls -lah /opt/centminmod/
total 20K
drwxr-xr-x. 2 root root   89 Mar 11 08:06 .
drwxr-xr-x. 5 root root   49 Mar 11 08:15 ..
-rwxr-xr-x. 1 root root 9.7K Mar 11 08:06 first-login.sh
-rw-r--r--. 1 root root  380 Mar 11 08:06 memcache-admin-login.txt
-rw-r--r--. 1 root root  335 Mar 11 08:06 php-info-password.txt
```
where /opt/centminmod/first-login.sh would be triggered by entry in /root/.bashrc which will prompt for email, hostname and regenerate memcached, and mysql passwords and at the end override the modified /root/.bashrc with default

```
cp -f /etc/skel/.bashrc /root/.bashrc
```

however, if i rebuild an already launched droplet with the snapshot image, the first-login.sh prompt doesn't fully happen but some of the script does get run to regenerate the memcache and php passwords

the packer provisioners section is setup as

```
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "mkdir -p /opt/centminmod"
      ]
    },
    {
      "type": "file",
      "source": "scripts/first-login.sh",
      "destination": "/opt/centminmod/"
    },
    {
      "type": "shell",
      "inline": [
        "chmod +x /opt/centminmod/first-login.sh",
        "echo '/opt/centminmod/first-login.sh' >> /root/.bashrc"
      ]
    },
    {
      "type": "shell",
      "environment_vars": [
        "INSTALL_ELREPO={{user `install_elrepo`}}",
        "INSTALL_BBR={{user `install_bbr`}}",
        "INSTALL_DOCKER={{user `install_docker`}}",
        "INSTALL_REDIS={{user `install_redis`}}",
        "INSTALL_AUDITD={{user `install_auditd`}}",
        "INSTALL_BROTLI={{user `enable_brotli`}}",
        "INSTALL_PHPPGO={{user `enable_phppgo`}}",
        "INSTALL_LOGROTATEZSTD={{user `enable_logrotate_zstd`}}",
        "INSTALL_PHPFPMSYSTEMD={{user `enable_phpfpm_systemd`}}"
      ],
      "scripts": [
        "scripts/cmm-install.sh"
      ],
      "remote_folder": "/home",
      "remote_file": "script_1.sh"
    }
  ]
```

**Comment by ryanpq** [comment]
One option for the first login script would be to add something to /var/lib/cloud/per-instance that writes the call to .bashrc with the script running the copy back of .bashrc from skel when it completes it's work.  Per-instance would be triggered when a new droplet is created from a snapshot and can ensure that the first login script is run anytime the image is deployed to a new droplet including via a snapshot.

**Comment by centminmod** [comment]
thanks @ryanpq but would using per-instance method work if first-login.sh script is interactive and requires user input and requires users eyes on the info presented ?

I think i found a way - set `skip-clean` to true in packer https://www.packer.io/docs/provisioners/shell.html#skip_clean and instead of letting packer clean up the helper scripts, I do the clean up routine in my first-login.sh script. This way there's no premature new ssh sessions opened before the droplet's first ssh login. Testing that theory out with a new build.

> skip_clean (boolean) - If true, specifies that the helper scripts uploaded to the system will not be removed by Packer. This defaults to false (clean scripts from the system).

**Comment by ryanpq** [comment]
For an interactive script to run on first login what I would do is add a line to my per-instance script that inserts the call to the first-login script in /opt to the end of .bashrc.  That way when the image or a snapshot of it is first booted on a new droplet the .bashrc is updated and when the user logs in the script runs and removes the call from .bashrc when it's done.

**Comment by centminmod** [comment]
Thanks. The `skip-clean` method worked too and got the first login prompts. But using per-instance looks cleaner 👍  Try it out now :)
