### ISSUE TITLE
Provide instructions on recommended method to use Packer [template]

### ISSUE THREAD

**Issue by arosales** [digitalocean/marketplace-partners#37]
Reading through:
https://github.com/digitalocean/marketplace-partners/blob/master/marketplace_docs/build-an-image-fabric.md

I was unable to find instructions on the recommended method to use Packer in a DO one-click build process. While we have https://github.com/digitalocean/marketplace-partners/tree/master/marketplace_docs/templates/Packer it would be nice to link the Packer instructions with the Fabric documentation with our recommendations on how to set up a DO one-click build pipeline.

**Comment by jgannondo** [comment]
@arosales Does this (https://github.com/digitalocean/marketplace-partners/tree/master/packer) meet the need? Asking as it's been several months since the ticket was opened and I know @ryanpq had made some improvements since then.

**Comment by scottcrawford03** [comment]
see @jgannondo comment above!
