### ISSUE TITLE
In some cases, when security updates are needed the updates are not listed as expected

### ISSUE THREAD

**Issue by jgannondo** [digitalocean/marketplace-partners#41]
See attached jpg, submitted by a Vendor. 

In this case, they are seeing a FAIL related to missing security updates, but then the script doesn't print out which ones are missing.
![fail](https://user-images.githubusercontent.com/28159071/54310366-9b124980-45a8-11e9-807e-1d5f5f1c2462.jpg)

**Comment by vania-pooh** [comment]
@jgannondo having the same message with some 8 security updates available here is what I'm getting using standard APT commands:
```
root@test:~# DEBIAN_FRONTEND=noninteactive apt-get -y upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  linux-headers-generic linux-headers-virtual linux-image-virtual linux-virtual
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

Without this fix I'm unable to submit my image to DigitalOcean. So this is a blocker.

Another interesting question is when do you expect to run this script: before creating a snapshot or after it? In the first case you get history filled by running a command, in the second case your VM has an SSH key.

**Comment by jgannondo** [comment]
@vania-pooh thanks for letting us know. 

I don't want a fix to the script to be a blocker for you to list your app, so in parallel can you submit your listing and refer to this thread in your submission (in the section when you paste the output of img_check.sh, which you should still do)? 

I can run the apt-get manually on my end after I boot your image to validate as you have done. Thanks! // @ryanpq

**Comment by vania-pooh** [comment]
@jgannondo sure, will do. Thank you.

**Comment by ryanpq** [comment]
The update check portion of img_check.sh has been rewritten and package counts and lists should now match when security updates are available.  Extra line break characters in the output of the package list from apt was causing update counts and lists not to match after being evaluated.  By correcting for these additional line breaks in the apt output we are now seeing consistently matching counts and lists.
