### ISSUE TITLE
packer.io built droplet FAILED img_check.sh

### ISSUE THREAD

**Issue by centminmod** [digitalocean/marketplace-partners#43]
With packer.io built droplet snapshot images, packer will insert it's own SSH key during the build but automatically remove it after the build is complete.

But I am running img_check.sh at end of packer.io build so the packer SSH key is still detected. Is this okay for submission ? As it only picks up packer's SSH key prior to packer cleaning up after itself and auto removing that SSH key.

```
    digitalocean: Checking the root account...
    digitalocean: [PASS] User root has no password set.
    digitalocean: [FAIL] User root has a populated authorized_keys file in /root/.ssh/authorized_keys
    digitalocean: File Contents:
    digitalocean: ssh-rsa AAAAB3Nza*****
    digitalocean: --------------
```

and at end of packer run where that temp SSH key is deleted

```
    digitalocean: ---------------------------------------------------------------------------------------------------
    digitalocean: Some critical tests failed.  These items must be resolved and this scan re-run before you submit your image to the marketplace.
    digitalocean:
    digitalocean:
    digitalocean:
    digitalocean: Fri Mar 22 01:43:11 UTC 2019
==> digitalocean: Gracefully shutting down droplet...
==> digitalocean: Creating snapshot: centos7-packer-snapshot-1553217043
==> digitalocean: Waiting for snapshot to complete...
==> digitalocean: Destroying droplet...
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' finished.
```

**Comment by jgannondo** [comment]
@centminmod thanks for checking on this. Not a problem at all as the snapshot itself wouldn't have the key lingering. Just note when you submit that the FAIL condition is the Packer key. Thanks much! // @ryanpq

**Comment by centminmod** [comment]
Cheers @jgannondo for the confirmation :)

**Comment by Amygos** [comment]
Packer only remove the ssh temporary key from your account, **not from the droplet**, so you have to manually cleanup.

For example:

Packer config
```json
{
  "builders": [{
    "type": "digitalocean",
    "image": "centos-7-x64",
    "region": "ams3",
    "size": "s-1vcpu-1gb",
    "ssh_username": "root",
    "snapshot_name": "app-{{timestamp}}"
  }]
}
```
On the machine created from snapshot:
```
[root@app-1557310908-s-1vcpu-1gb-ams3-01 ~]# cat .ssh/authorized_keys | wc
      2       5     776
```
As you can see there are two ssh keys, one created by packer and the other taken from user account.

**Comment by centminmod** [comment]
@Amygos ah thanks for heads up ! Luckily still testing my marketplace image internally before submission to the marketplace :)

**Comment by ryanpq** [comment]
It sounds like this issue is resolved.  It may be worth looking into whether we can detect that the validation script is running within a build process like this so we can account for quirks of the tooling and provide a WARN rather than a FAIL for this entry if running from within a packer build.
