### ISSUE TITLE
img_check.sh: Script should not emit FAIL condition on a zero byte ssh key file

### ISSUE THREAD

**Issue by jgannondo** [digitalocean/marketplace-partners#49]
AFAIK a zero byte file does not cause a vulnerability, so we should probably change this to a WARN instead of a FAIL.

**Comment by ryanpq** [comment]
We could but I'm not aware of any use case for a zero byte ssh key file that would necessitate the change.

**Comment by jgannondo** [comment]
@ryanpq I've seen at least a couple of instances of zero-byte key files in Vendor submitted images. So I think it's worth adding a check for this condition and making it a WARN (or maybe, not even a WARN) and also not a FAIL.

**Comment by ryanpq** [comment]
Sounds good.  We'll add an additional check if a file is found so that we will WARN if the file is empty and FAIL if it is not.
