### ISSUE TITLE
Question: using the Docker Droplet as the base image for marketplace contributions

### ISSUE THREAD

**Issue by mkjsix** [digitalocean/marketplace-partners#52]
Is it possibile to contribute a Docker image to the marketplace instead of installing directly to the OS? Our product is highly optimized for Docker and it would be a lot easier to create a new Droplet starting from the Docker droplet instead of installing the software from scratch on a Linux base image.

**Comment by ryanpq** [comment]
Yes, though integrating the docker installation into your image build scripts would be the preferred option over using the DO Docker image.  This will prevent any potential future changes to the DO one-click from causing issues with your builds.  If you reach out to the DO marketplace team directly we can provide the relevant scripts used for our Docker one-click so you can integrate those functions into your build.
