### ISSUE TITLE
User root has a password set on their account

### ISSUE THREAD

**Issue by carmo-evan** [digitalocean/marketplace-partners#54]
I've run the script that's meant to clean up all keys, passwords, history, etc. multiple times. However, I still get the error `User root has a password set on their account` when running the validation. I've checked /etc/shadow and there's no password in there.

**Comment by ryanpq** [comment]
The root password detection is based on a direct parsing of the shadow file.  It's possible that we missed one potential case in this routine.  Please reach out to the team directly so we can take a closer look and update the validation script if needed.

**Comment by jgannondo** [comment]
@carmo-evan  are you still facing this issue?

**Comment by carmo-evan** [comment]
Hi,

I am no longer working on this project.

Thank you,

Evan
