### ISSUE TITLE
[Feature Request] Check /var/log for any key values

### ISSUE THREAD

**Issue by arosales** [digitalocean/marketplace-partners#60]
In some cases /var/log/cloud-init-output.log can contain key values. Thus, this ticket is to check if any ssh key values are still left in log files and if so `Fail` the image check script.

**Comment by arosales** [comment]
DigitalOcean reference = https://jira.internal.digitalocean.com/browse/MP-845

**Comment by ryanpq** [comment]
This makes sense as an improvement to the existing log checking function.  Right now the function will warn for populated log files in /var/log/ so adding an additional check for the string "ssh-rsa" in the cloud-init-output.log should be a pretty straightforward addition.

**Comment by arosales** [comment]
the string `ssh-rsa` wouldn't have found the issue but `SHA256` or just looking for `key` would have. The latter being more general.

**Comment by scottcrawford03** [comment]
sounds good i'll add the look up!

**Comment by scottcrawford03** [comment]
@arosales do you have an example of a log file that had a key that should've been failed? I am afraid just searching for `key` will be too generic and bring some failures that we wouldn't want to fail on.

**Comment by arosales** [comment]
I don't have access to the droplet that had the example. Perhaps we `warn` on `key` but `error` on `SHA256` in the scope of /var/log
