### ISSUE TITLE
journalctl "no journal files found" on startup with the packer script

### ISSUE THREAD

**Issue by nhooyr** [digitalocean/marketplace-partners#68]
Code at https://github.com/codercom/do-marketplace-partners/commit/3ce49839526658375a3e18e8514e8789465ee111

Just run `packer build marketplace-image.json` in the packer subdir and then try and run `journalctl -fu code-server` on the resulting droplet.

Same problem with master on this repo.

**Comment by nhooyr** [comment]
Disabling the cleanup and img_check script fixes this. Didn't test disabling just one of them. Related #28

**Comment by nhooyr** [comment]
No idea what's causing this actually, disabling he cleanup and img_check scripts does not fix this.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.

**Comment by Mohammed90** [comment]
I actually faced the same issue last week

**Comment by keatz55** [comment]
I have also encountered this recently. After running the new droplet, I have to run `systemctl restart systemd-journald` and then it works as expected.
