### ISSUE TITLE
img_check.sh: Ubuntu ufw check is not correct

### ISSUE THREAD

**Issue by pinheadmz** [digitalocean/marketplace-partners#74]
On my instance at least, when I run the command

`ufw status | sed -e "s/^Status:\ //"`

...it returns much more than a single word!

```
active To Action From -- ------ ---- 22/tcp ALLOW Anywhere 8333/tcp ALLOW Anywhere 22/tcp (v6) ALLOW Anywhere (v6) 8333/tcp (v6) ALLOW Anywhere (v6)
```

...and so the `==` check fails here:

https://github.com/digitalocean/marketplace-partners/blob/60aa691dd3c3a7464d1bd8ffe54357968a0302e3/scripts/img_check.sh#L332-L337

**Comment by LuluGO** [comment]
Could be fixed like this maybe:
```
    if [[ $OS == "Ubuntu" ]]; then
      fw="ufw"
      ufwa=$(ufw status |head -1| sed -e "s/^Status:\ //")
      if [[ $ufwa == "active" ]]; then
```

**Comment by wadenick** [comment]
Hi @LuluGO, thank you for this suggestion, I've tested on both support Ubuntu distros and piping through head -1 for the first line works well as a patch. We appreciate your assist! 💙 🦈 🦈 🦈
