### ISSUE TITLE
Script throws an error when apt-check does not exist

### ISSUE THREAD

**Issue by jgannondo** [digitalocean/marketplace-partners#8]
`./img_check.sh: line 299: [[: ./img_check.sh: line 298: /usr/lib/update-notifier/apt-check: No such file or directory: syntax error: operand expected (error token is "./img_check.sh: line 298: /usr/lib/update-notifier/apt-check: No such file or directory")`

**Comment by ryanpq** [comment]
https://github.com/digitalocean/marketplace-partners/pull/14

PR submitted to address this issue.
