### ISSUE TITLE
Supported OS: FreeBSD

### ISSUE THREAD

**Issue by oxr463** [digitalocean/marketplace-partners#88]
As FreeBSD is now supported on DO, it makes sense that one should be able to create such an appliance for the marketplace.

**Comment by scottcrawford03** [comment]
Thanks for reaching out and sorry for the long wait for reply.

I have kicked off the conversation with my team on this and have logged a ticket to dig into it deeper.

**Comment by arosales** [comment]
@oxr463 thanks for the feedback. While we would love to have all 1-clicks supported across all base OSes it does increase our support/test matrix. As a Marketplace community I would suggest we focus on the app experience on-top of Linux (Ubuntu/CentOS).

@oxr463 as a 1-click user is there an experience lacking in the current 1-clicks based on Ubuntu and CentOS?
