### ISSUE TITLE
What is meant by "Submit your final image"?

### ISSUE THREAD

**Issue by erlend-sh** [digitalocean/marketplace-partners#99]
Hi! We've been going through the Marketplace submission process and got a little bit confused at some points.

We have completed steps 1-3 and have the repo ready here:
https://github.com/meilisearch/meilisearch-digital-ocean

The 4th and final step goes as follows:

> Submit your final image to the Marketplace team for review.

It doesn't link anywhere. Do you mean submit here?
https://marketplace.digitalocean.com/vendors

I entered the form on /vendors and got this mail back:

> Thanks for your interest in the DigitalOcean Marketplace!
> 
> You can find more information on getting started with your listing in the DigitalOcean Marketplace, [here](https://pages.news.digitalocean.com/n/Q0bD0jI0Ek36c2XeV00sIu0). Once you’ve had a chance to review, please feel free to [schedule 30 minutes](https://pages.news.digitalocean.com/n/lCIcZ0006iju0D3VI0X0m2E) for us to discuss and confirm the next steps.
> 
> I look forward to speaking.

This was a bit confusing as well because I couldn't tell if this call is optional or a required step towards entering the marketplace. Is it "feel free" as in *do it*? 😄 

In any case I've got a call set up for next week so I expect that'll clear up any misunderstandings we might have had.

**Comment by jgannondo** [comment]
@erlend-sh thank you for reaching out. You're right, we could be more clear on how the submission process works. I've submitted https://github.com/digitalocean/marketplace-partners/pull/100 as an improvement. Hope this helps and let me know if you have any other questions.

**Comment by jgannondo** [comment]
Closing as we merged the PR. Please feel free to open another Issue if you feel we didn't adequately explain the process, always looking to improve! Thanks :)

**Comment by erlend-sh** [comment]
That is much clearer, thanks a bunch!
